"""Ajout unit_price à OrderItem

Revision ID: 19045d33d0ac
Revises: 2952939cce9c
Create Date: 2025-06-23 22:23:26.928885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19045d33d0ac'
down_revision = '2952939cce9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
