"""Ajout commission et seller_amount à OrderItem

Revision ID: 2952939cce9c
Revises: c22bd73342cf
Create Date: 2025-06-23 17:22:15.639934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2952939cce9c'
down_revision = 'c22bd73342cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seller_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('seller_amount')
        batch_op.drop_column('commission')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
