"""Ajout promo par variante

Revision ID: 2f5739d07097
Revises: 5ba4f9735bb9
Create Date: 2025-07-03 22:32:05.767185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5739d07097'
down_revision = '5ba4f9735bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('promo_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('promo_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_column('promo_end')
        batch_op.drop_column('promo_start')
        batch_op.drop_column('discount_price')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
