"""empty message

Revision ID: 340113674f41
Revises: b321a6deeb55
Create Date: 2025-08-01 02:23:50.088871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340113674f41'
down_revision = 'b321a6deeb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_cloudinary_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_url')

    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_url')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('video_cloudinary_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
