"""Ajout du modèle PackAchat

Revision ID: 6364abb47676
Revises: e1b4fefe7e95
Create Date: 2025-07-14 20:05:34.175214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6364abb47676'
down_revision = 'e1b4fefe7e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_achat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('moyen_paiement', sa.String(length=10), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pack_achat')
    # ### end Alembic commands ###
