"""Ajout de champs currency dans le modèle user

Revision ID: 6bee363eed5f
Revises: 16f40182c6f8
Create Date: 2025-07-28 13:45:01.743252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bee363eed5f'
down_revision = '16f40182c6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
