"""Ajout des champs pour Orange Money et Wave

Revision ID: 820c99078ddc
Revises: f8f2759ce178
Create Date: 2025-07-28 02:17:52.719315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820c99078ddc'
down_revision = 'f8f2759ce178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orange_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('orange_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wave_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wave_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('wave_id')
        batch_op.drop_column('wave_number')
        batch_op.drop_column('orange_id')
        batch_op.drop_column('orange_number')

    # ### end Alembic commands ###
