"""Ajout table annonces sponsorisées

Revision ID: 821e729c2271
Revises: 38e59b2fafc3
Create Date: 2025-07-06 09:26:56.517399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821e729c2271'
down_revision = '38e59b2fafc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sponsored', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('is_sponsored')

    # ### end Alembic commands ###
