"""Ajout champ video_filename à Listing

Revision ID: 8b31cb93ec8a
Revises: 1ebdf79d4788
Create Date: 2025-06-27 17:06:33.345222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b31cb93ec8a'
down_revision = '1ebdf79d4788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('video_filename')

    # ### end Alembic commands ###
