"""Ajout des champs poids, dimensions, contenu_pack, tags, date_expiration

Revision ID: ae59b675e199
Revises: 8b31cb93ec8a
Create Date: 2025-06-28 21:24:57.625886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae59b675e199'
down_revision = '8b31cb93ec8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poids', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contenu_pack', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('date_expiration', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('date_expiration')
        batch_op.drop_column('tags')
        batch_op.drop_column('contenu_pack')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('poids')

    # ### end Alembic commands ###
