"""Ajout des informations Mobile Money

Revision ID: b321a6deeb55
Revises: f4a9e8980c99
Create Date: 2025-07-30 12:14:40.007382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b321a6deeb55'
down_revision = 'f4a9e8980c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_money_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mobile_money_holder', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wave_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wave_holder', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wave_holder')
        batch_op.drop_column('wave_number')
        batch_op.drop_column('mobile_money_holder')
        batch_op.drop_column('mobile_money_number')

    # ### end Alembic commands ###
