"""Ajout frais de livraison dans Listing

Revision ID: c22bd73342cf
Revises: 9bad7431af8b
Create Date: 2025-06-23 15:46:33.819822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22bd73342cf'
down_revision = '9bad7431af8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_fee', sa.Float(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('delivery_fee')

    # ### end Alembic commands ###
