"""Ajout champs totals dans Order

Revision ID: d77dcfb55e15
Revises: ae59b675e199
Create Date: 2025-06-29 22:04:07.633237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77dcfb55e15'
down_revision = 'ae59b675e199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rub', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_delivery_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_commission_rub', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_usdt', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('total_usdt')
        batch_op.drop_column('total_commission_rub')
        batch_op.drop_column('total_delivery_fee')
        batch_op.drop_column('total_rub')

    # ### end Alembic commands ###
