"""Ajout du modèle AnnoncePack

Revision ID: e1b4fefe7e95
Revises: 821e729c2271
Create Date: 2025-07-14 19:23:28.704580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b4fefe7e95'
down_revision = '821e729c2271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annonce_pack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_annonces', sa.Integer(), nullable=False),
    sa.Column('annonces_utilisées', sa.Integer(), nullable=False),
    sa.Column('date_achat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annonce_pack')
    # ### end Alembic commands ###
