"""Ajout du ondelete cascade pour utilisateur_id

Revision ID: f4a9e8980c99
Revises: 6bee363eed5f
Create Date: 2025-07-29 15:13:04.994240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a9e8980c99'
down_revision = '6bee363eed5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adresse_livraison', schema=None) as batch_op:
        batch_op.alter_column('utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('adresse_livraison_utilisateur_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['utilisateur_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adresse_livraison', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('adresse_livraison_utilisateur_id_fkey'), 'user', ['utilisateur_id'], ['id'])
        batch_op.alter_column('utilisateur_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
